export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const LOGOUT = 'LOGOUT';
export const GET_CREATORS = 'GET_CREATORS';
export const GET_BUSINESSES = 'GET_BUSINESSES';

export const CREATOR_ERROR = 'CREATOR_ERROR';
export const BUSINESS_ERROR = 'BUSINESS_ERROR';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
